development:
  cloud_name: dezxhm3xp
  api_key: '485231573142622'
  api_secret: "QOjZBJ7MmtP18e610P3W1VMEuDc"
production:
  cloud_name: dezxhm3xp
  api_key: '485231573142622'
  api_secret: "QOjZBJ7MmtP18e610P3W1VMEuDc"
test:
  cloud_name: dezxhm3xp
  api_key: '485231573142622'
  api_secret: "QOjZBJ7MmtP18e610P3W1VMEuDc"